import os

def _connect_paths(*paths):
    return os.path.join(*paths)

ASSETS_FOLDER_PATH = "assets"
CONSTANTS_FOLDER_PATH = "constants"
GRAPHICS_FOLDER_PATH = "graphics"
OUTPUT_FOLDER_PATH = "output"
UTILITIES_FOLDER_PATH = "utilities"

SHEET_PATH = _connect_paths(ASSETS_FOLDER_PATH, "instruction_set.png")
CONSOLE_TEXT_PATH = _connect_paths(OUTPUT_FOLDER_PATH, "console_output.txt")

PROGRAM_STRUCTURE_CHECKLIST = [
    ASSETS_FOLDER_PATH,
    CONSTANTS_FOLDER_PATH,
    GRAPHICS_FOLDER_PATH,
    UTILITIES_FOLDER_PATH
]

PYCACHE_INCLUDERS_CHECKLIST = [
    CONSTANTS_FOLDER_PATH,
    GRAPHICS_FOLDER_PATH,
    UTILITIES_FOLDER_PATH
]

PRE_EXISTING_CHECKLIST = [
    OUTPUT_FOLDER_PATH
]